---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2 on ubuntu nodes
    apt:
       name: apache2
       state: present

  - name:  i want to start webserver on ununtu nodes  
    service:
       name: apache2
       state: started